- name: create external net
  os_network:
    auth: "{{ os_auth }}"
    name: extnet
    external: true
    provider_physical_network: datacentre
    provider_network_type: flat

- name: create external subnet
  os_subnet:
    auth: "{{ os_auth }}"
    name: extsubnet
    network_name: extnet
    allocation_pool_start: 192.168.24.129
    allocation_pool_end: 192.168.24.150
    cidr: 192.168.24.0/24
    gateway_ip: 192.168.24.1

- name: create demo net
  os_network:
    auth: "{{ os_auth }}"
    name: demonet

- name: create demo subnet
  os_subnet:
    auth: "{{ os_auth }}"
    name: demosubnet
    network_name: demonet
    allocation_pool_start: 192.168.30.10
    allocation_pool_end: 192.168.30.63
    cidr: 192.168.30.0/24
    gateway_ip: 192.168.30.1
    dns_nameservers: "{{ dns_servers }}"

- name: create demo router
  os_router:
    auth: "{{ os_auth }}"
    name: demorouter
    network: extnet
    interfaces:
      - demosubnet

- name: create demo flavor
  os_nova_flavor:
    auth: "{{ os_auth }}"
    name: demoflavor
    ram: 6144
    vcpus: 2
    disk: 30

- name: create demo security group
  os_security_group:
    auth: "{{ os_auth }}"
    name: demogroup

- name: demo security group allow all IPv4 with external
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: demogroup
    direction: ingress
    ethertype: IPv4
    remote_ip_prefix: '0.0.0.0/0'
  with_items:
    - ingress
    - egress

- name: demo security group allow all IPv4 within group
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: demogroup
    direction: egress
    ethertype: IPv4
    remote_group: demogroup
  with_items:
    - ingress
    - egress

- name: fetch Fedora cloud image
  get_url:
    dest: "{{ lookup('env', 'HOME') }}/fedora27.qcow2"
    url: "https://download.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2"

- name: upload Fedora cloud image to glance
  os_image:
    auth: "{{ os_auth }}"
    name: fedora27
    filename: "{{ lookup('env', 'HOME') }}/fedora27.qcow2"

- name: create demo keypair
  os_keypair:
    auth: "{{ os_auth }}"
    name: demokey
    public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

- name: create demo servers
  os_server:
    auth: "{{ os_auth }}"
    name: "demo{{item}}"
    auto_ip: yes
    flavor: demoflavor
    image: fedora27
    key_name: demokey
    network: demonet
    security_groups: demogroup
    timeout: 600
  with_sequence: start=0 count={{server_count}}
